spring:
  application:
    name: gallery
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gallery
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: "warn"
    org.springframework.web: "debug"